In [11]:
import numpy as np

In [14]:
import os
os.path.abspath('.')

'C:\\Users\\Alvin'

In [19]:
matrixA=[]

for i in open("/Users/Alvin/Desktop/ML_lhy/data1/matrixA.txt"):
    row=[int(x) for x in i.split(",") ]
    matrixA.append(row)



In [23]:
print(matrixA)

[[8, 4, 2, 3, 5, 4, 4, 2, 6, 6, 7, 1, 3, 3, 5, 6, 8, 3, 9, 4, 9, 9, 2, 5, 3, 2, 6, 6, 5, 2, 6, 7, 7, 5, 9, 3, 5, 8, 8, 9, 5, 7, 7, 8, 1, 6, 3, 8, 4, 3]]


In [26]:
matrixB=[]

In [27]:
for j in open("/Users/Alvin/Desktop/ML_lhy/data1/matrixB.txt"):
    row=[int(x) for x in j.split(",") ]
    matrixB.append(row)


In [28]:
print(matrixB)

[[7, 3, 2, 9, 9, 2, 3, 3, 1, 3], [1, 8, 5, 2, 8, 7, 9, 6, 2, 3], [3, 4, 7, 8, 8, 4, 2, 8, 8, 7], [4, 7, 9, 7, 4, 4, 2, 7, 1, 1], [6, 4, 4, 7, 3, 7, 6, 9, 3, 6], [7, 7, 7, 5, 1, 6, 1, 5, 7, 1], [4, 4, 9, 6, 7, 2, 1, 8, 8, 7], [3, 8, 7, 8, 2, 3, 6, 8, 9, 9], [8, 9, 6, 9, 3, 2, 7, 6, 3, 8], [5, 6, 5, 3, 4, 4, 4, 4, 2, 1], [3, 5, 2, 3, 7, 6, 2, 8, 8, 3], [5, 1, 2, 5, 9, 8, 1, 7, 8, 1], [3, 4, 9, 5, 6, 7, 5, 7, 5, 5], [3, 8, 2, 5, 8, 6, 9, 3, 3, 8], [9, 3, 8, 4, 2, 8, 4, 9, 5, 1], [6, 7, 1, 6, 1, 8, 7, 3, 3, 6], [4, 7, 3, 3, 9, 1, 6, 7, 8, 3], [6, 7, 8, 7, 8, 1, 1, 4, 6, 1], [6, 4, 9, 7, 5, 7, 5, 2, 4, 9], [8, 4, 2, 8, 3, 2, 6, 6, 9, 2], [1, 4, 3, 7, 1, 7, 9, 9, 6, 8], [7, 4, 3, 9, 8, 7, 4, 3, 3, 8], [8, 9, 2, 5, 6, 4, 2, 8, 2, 9], [1, 5, 9, 9, 6, 8, 7, 5, 9, 9], [2, 8, 2, 8, 5, 3, 6, 8, 6, 5], [6, 5, 2, 1, 6, 4, 4, 4, 6, 9], [8, 7, 3, 3, 1, 2, 7, 5, 1, 6], [8, 4, 4, 8, 4, 5, 8, 9, 6, 3], [3, 3, 9, 8, 3, 6, 6, 2, 4, 5], [4, 5, 2, 4, 8, 8, 7, 4, 2, 7], [9, 3, 2, 3, 6, 9, 9, 9, 8, 6], [3, 6, 

In [29]:
matrixA = np.array(matrixA)

In [30]:
matrixB = np.array(matrixB)

In [31]:
print(matrixA)
print(matrixB)

[[8 4 2 3 5 4 4 2 6 6 7 1 3 3 5 6 8 3 9 4 9 9 2 5 3 2 6 6 5 2 6 7 7 5 9 3
  5 8 8 9 5 7 7 8 1 6 3 8 4 3]]
[[7 3 2 9 9 2 3 3 1 3]
 [1 8 5 2 8 7 9 6 2 3]
 [3 4 7 8 8 4 2 8 8 7]
 [4 7 9 7 4 4 2 7 1 1]
 [6 4 4 7 3 7 6 9 3 6]
 [7 7 7 5 1 6 1 5 7 1]
 [4 4 9 6 7 2 1 8 8 7]
 [3 8 7 8 2 3 6 8 9 9]
 [8 9 6 9 3 2 7 6 3 8]
 [5 6 5 3 4 4 4 4 2 1]
 [3 5 2 3 7 6 2 8 8 3]
 [5 1 2 5 9 8 1 7 8 1]
 [3 4 9 5 6 7 5 7 5 5]
 [3 8 2 5 8 6 9 3 3 8]
 [9 3 8 4 2 8 4 9 5 1]
 [6 7 1 6 1 8 7 3 3 6]
 [4 7 3 3 9 1 6 7 8 3]
 [6 7 8 7 8 1 1 4 6 1]
 [6 4 9 7 5 7 5 2 4 9]
 [8 4 2 8 3 2 6 6 9 2]
 [1 4 3 7 1 7 9 9 6 8]
 [7 4 3 9 8 7 4 3 3 8]
 [8 9 2 5 6 4 2 8 2 9]
 [1 5 9 9 6 8 7 5 9 9]
 [2 8 2 8 5 3 6 8 6 5]
 [6 5 2 1 6 4 4 4 6 9]
 [8 7 3 3 1 2 7 5 1 6]
 [8 4 4 8 4 5 8 9 6 3]
 [3 3 9 8 3 6 6 2 4 5]
 [4 5 2 4 8 8 7 4 2 7]
 [9 3 2 3 6 9 9 9 8 6]
 [3 6 6 3 8 2 2 1 2 2]
 [5 8 4 3 1 1 4 4 2 1]
 [8 4 5 4 7 1 8 6 2 3]
 [8 9 5 1 9 7 8 1 9 2]
 [2 4 3 2 7 6 7 9 7 2]
 [2 2 9 1 8 6 9 7 3 9]
 [2 5 3 8 2 7 1 1 4 9]
 [6 5 6 6 3 1 4 9 3 

In [32]:
ans = matrixA.dot(matrixB)

In [33]:
print(ans)

[[1349 1411 1378 1434 1309 1301 1295 1528 1226 1332]]


In [34]:
ans.sort(axis=1)
print(ans)

[[1226 1295 1301 1309 1332 1349 1378 1411 1434 1528]]


In [35]:
np.savetxt("/Users/Alvin/Desktop/ML_lhy/data1/Q1_ans.txt", ans, fmt="%d", delimiter="\r\n")